# Generated by Django 4.2.17 on 2024-12-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home / ہوم'), ('about', 'About / بارے میں'), ('contact', 'Contact / رابطہ کریں'), ('services', 'Services / خدمات'), ('faq', 'FAQ / سوالات'), ('privacy', 'Privacy Policy / رازداری کی پالیسی'), ('terms', 'Terms and Conditions / شرائط و ضوابط'), ('help', 'Help / مدد')], max_length=50, verbose_name='Page')),
                ('language', models.CharField(choices=[('english', 'English'), ('urdu', 'Urdu')], max_length=10, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Page Title')),
                ('content', models.TextField(verbose_name='Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='Imam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=255, verbose_name='Imam Name in English')),
                ('name_urdu', models.CharField(max_length=255, verbose_name='امام کا نام اردو میں')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=255, verbose_name='Keyword in English')),
                ('name_urdu', models.CharField(max_length=255, verbose_name='کلیدی لفظ اردو میں')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=255, verbose_name='Book Name in English')),
                ('name_urdu', models.CharField(max_length=255, verbose_name='کتاب کا نام اردو میں')),
                ('keywords', models.ManyToManyField(related_name='reference_books', to='myapp.keyword', verbose_name='Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_search_count', models.IntegerField(default=0, verbose_name='English Search Count')),
                ('urdu_search_count', models.IntegerField(default=0, verbose_name='Urdu Search Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='myapp.keyword', verbose_name='Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=255, verbose_name='Catalogue Title in English')),
                ('title_urdu', models.CharField(max_length=255, verbose_name='کیٹلاگ کا عنوان اردو میں')),
                ('description_english', models.TextField(blank=True, null=True, verbose_name='Description in English')),
                ('description_urdu', models.TextField(blank=True, null=True, verbose_name='تفصیل اردو میں')),
                ('imam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='myapp.imam', verbose_name='Imam')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='myapp.keyword', verbose_name='Keyword')),
                ('reference_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='myapp.referencebook', verbose_name='Reference Book')),
            ],
        ),
    ]
