# Generated by Django 4.2.17 on 2024-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_referencebook_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Google Analytics Dashboard', editable=False, max_length=255)),
            ],
        ),
    ]
