# Generated by Django 4.2.17 on 2024-12-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_googleanalyticsredirect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAnalyticsRedirect',
        ),
    ]
